export type Lang = "en" | "ta";

export const labels = {
  en: {
    // Landing / nav
    livestock: "Livestock Management",
    livestockShort: "Livestock",
    cows: "Cows",
    goats: "Goats",
    hens: "Hens",
    generalExpenses: "General Expenses",
    generalExpensesFull: "General Livestock Expenses",
    backToCows: "Back to Cows",
    backToGoats: "Back to Goats",
    backToHens: "Back to Hens",
    backToLivestock: "Back to Livestock",

    // Common actions
    addCow: "Add Cow",
    addGoat: "Add Goat",
    addHen: "Add Hen",
    addExpense: "Add Expense",
    addSale: "Add Sale",
    addPayment: "Add Payment",
    save: "Save",
    cancel: "Cancel",
    edit: "Edit",
    delete: "Delete",
    select: "Select",
    all: "All",
    allFarms: "All Farms",

    // Status / filters
    total: "Total",
    totalCows: "Total Cows",
    active: "Active",
    sold: "Sold",
    deceased: "Deceased",
    income: "Income",
    expense: "Expense",
    netPL: "Net P/L",
    monthMilkIncome: "Month Milk Income",
    monthExpenses: "Month Expenses",
    totalIncome: "Total Income",
    totalExpense: "Total Expense",

    // Form fields
    name: "Name",
    tagNumber: "Tag Number",
    breed: "Breed",
    gender: "Gender",
    male: "Male",
    female: "Female",
    dateOfBirth: "Date of Birth",
    purchaseDate: "Purchase Date",
    purchasePrice: "Purchase Price (₹)",
    weight: "Weight (kg)",
    status: "Status",
    notes: "Notes",
    soldDate: "Sold Date",
    soldPrice: "Sold Price",
    avgPerDay: "Avg/day",

    // Tabs
    overview: "Overview",
    milkCollection: "Milk Collection",
    payments: "Payments",
    expenses: "Expenses",
    details: "Details",

    // Milk rate
    currentMilkRate: "Current Milk Rate",
    currentRate: "Current Rate",
    perLitre: "litre",
    effectiveFrom: "effective from",
    updateRate: "Update Rate",
    newRate: "New Rate (₹)",
    effectiveFromDate: "Effective From",
    rateHistory: "Effective From | Rate per Litre",

    // Manual entry / OCR
    manualEntry: "Manual Entry",
    date: "Date",
    morning: "Morning (L)",
    evening: "Evening (L)",
    totalLitres: "Total",
    expectedIncome: "Expected Income",
    uploadMilkCard: "Upload Milk Card Photo",
    readingMilkCard: "Reading milk card...",
    saveAllRows: "Save All Rows",

    // Collection history
    collectionHistory: "Collection History",
    rate: "Rate",
    weekTotal: "Week Total",
    thisMonth: "This Month",
    goToPayments: "Go to Payments",
    noRecordsYet: "No records yet",

    // Payments
    totalExpected: "Total Expected",
    totalReceived: "Total Received",
    outstanding: "Outstanding",
    paymentDate: "Payment Date",
    periodFrom: "Period From",
    periodTo: "Period To",
    milkmanName: "Milkman Name",
    expectedAmount: "Expected Amount (₹)",
    receivedAmount: "Received Amount (₹)",
    difference: "Difference",
    paymentStatus: "Payment Status",
    remarks: "Remarks",
    paid: "Paid",
    partiallyPaid: "Partially Paid",
    pending: "Pending",
    noPaymentsYet: "No payments yet",

    // Expenses
    riceFeed: "Rice Feed",
    normalFeed: "Normal Feed",
    otherExpense: "Other Expense",
    expenseType: "Expense Type",
    feed: "Feed",
    brownLeafRolls: "Brown Leaf Rolls",
    miscellaneous: "Miscellaneous",
    quantity: "Quantity",
    quantityOptional: "Quantity (kg, optional)",
    amount: "Amount (₹)",
    vendorName: "Vendor Name",
    description: "Description",
    other: "Other",
    unit: "Unit",
    expenseRecords: "Expense Records",
    noExpensesYet: "No expenses yet",
    dateAmountRequired: "Date and amount are required",
    veterinary: "Veterinary",
    medicine: "Medicine",
    vaccination: "Vaccination",
    ai: "AI",
    shedMaintenance: "Shed Maintenance",
    editPayment: "Edit Payment",
    qty: "Qty",
    type: "Type",

    // Income (Goat/Hen)
    salesHistory: "Sales History",
    rateperKg: "Rate per kg (₹)",
    rateperBird: "Rate per Bird (₹)",
    totalAmount: "Total Amount (₹)",
    buyerName: "Buyer Name",
    noSalesYet: "No sales yet",
    byWeight: "By Weight",
    perBird: "Per Bird",
    numberOfBirds: "Number of Birds",
    weightOrBirds: "Weight/Birds",
    saleType: "Sale Type",

    // General Expenses page
    farm: "Farm",
    farmLocation: "Farm Location",
    vendor: "Vendor",
    quoted: "Quoted",
    final: "Final",
    quotedAmount: "Quoted Amount (₹)",
    finalAmount: "Final Amount (₹, optional)",
    itemDescription: "Item Description",
    accepted: "Accepted",
    rejected: "Rejected",
    totalAccepted: "Total Accepted",
    totalPending: "Total Pending",
    totalRejected: "Total Rejected",
    finalAmountPrompt: "Status is Accepted — consider filling in the Final Amount",
    deleteConfirmExpense: "Delete this expense?",
    deleteConfirmSale: "Delete this sale?",
    deleteConfirmRecord: "Delete this record?",
    deleteConfirmPayment: "Delete this payment?",

    // Empty states
    noCowsYet: "No cows yet. Add one above.",
    noGoatsYet: "No goats yet. Add one above.",
    noHensYet: "No hens yet. Add one above.",
    nameGenderRequired: "Name and gender are required",
    dateRequired: "Date is required",
    rateDateRequired: "Rate and date are required",
    periodMilkmanRequired: "Date, period, and milkman name are required",
    collectionFieldsRequired: "Date, morning litres, and evening litres are required",
    paymentFieldsRequired: "Payment date and received amount are required",
    saveFailedMessage: "சேமிக்க முடியவில்லை. மீண்டும் முயற்சிக்கவும். / Could not save. Please try again.",
    electricity: "Electricity",
    water: "Water",
    labour: "Labour",
    equipment: "Equipment",
    repairs: "Repairs",
    transport: "Transport",
    allFarmsShort: "All Farms",
    editExpense: "Edit Expense",
  },
  ta: {
    livestock: "கால்நடை மேலாண்மை",
    livestockShort: "கால்நடை",
    cows: "பசுக்கள்",
    goats: "ஆடுகள்",
    hens: "கோழிகள்",
    generalExpenses: "பொது செலவுகள்",
    generalExpensesFull: "பொது கால்நடை செலவுகள்",
    backToCows: "பசுக்களுக்கு திரும்பு",
    backToGoats: "ஆடுகளுக்கு திரும்பு",
    backToHens: "கோழிகளுக்கு திரும்பு",
    backToLivestock: "கால்நடைக்கு திரும்பு",

    addCow: "பசு சேர்க்க",
    addGoat: "ஆடு சேர்க்க",
    addHen: "கோழி சேர்க்க",
    addExpense: "செலவு சேர்க்க",
    addSale: "விற்பனை சேர்க்க",
    addPayment: "பணம் சேர்க்க",
    save: "சேமி",
    cancel: "ரத்து",
    edit: "திருத்து",
    delete: "நீக்கு",
    select: "தேர்வு செய்க",
    all: "அனைத்தும்",
    allFarms: "அனைத்தும்",

    total: "மொத்தம்",
    totalCows: "மொத்தம்",
    active: "செயலில்",
    sold: "விற்றது",
    deceased: "இறந்தது",
    income: "வருமானம்",
    expense: "செலவு",
    netPL: "நிகர லாப/நஷ்டம்",
    monthMilkIncome: "இந்த மாத பால் வருமானம்",
    monthExpenses: "இந்த மாத செலவு",
    totalIncome: "மொத்த வருமானம்",
    totalExpense: "மொத்த செலவு",

    name: "பெயர்",
    tagNumber: "டேக் எண்",
    breed: "இனம்",
    gender: "பாலினம்",
    male: "ஆண்",
    female: "பெண்",
    dateOfBirth: "பிறந்த தேதி",
    purchaseDate: "வாங்கிய தேதி",
    purchasePrice: "வாங்கிய விலை (₹)",
    weight: "எடை (கிலோ)",
    status: "நிலை",
    notes: "குறிப்பு",
    soldDate: "விற்ற தேதி",
    soldPrice: "விற்ற விலை",
    avgPerDay: "சராசரி/நாள்",

    overview: "மேலோட்டம்",
    milkCollection: "பால் சேகரிப்பு",
    payments: "பணம்",
    expenses: "செலவுகள்",
    details: "விவரங்கள்",

    currentMilkRate: "தற்போதைய விலை",
    currentRate: "தற்போதைய விலை",
    perLitre: "லிட்டர்",
    effectiveFrom: "நடைமுறை முதல்",
    updateRate: "விலை புதுப்பி",
    newRate: "புதிய விலை (₹)",
    effectiveFromDate: "நடைமுறை முதல்",
    rateHistory: "நடைமுறை முதல் | விலை/லிட்டர்",

    manualEntry: "கையேடு பதிவு",
    date: "தேதி",
    morning: "காலை (லி)",
    evening: "மாலை (லி)",
    totalLitres: "மொத்தம்",
    expectedIncome: "எதிர்பார்க்கும் வருமானம்",
    uploadMilkCard: "பால் அட்டை பதிவேற்றம்",
    readingMilkCard: "பால் அட்டையைப் படிக்கிறது...",
    saveAllRows: "அனைத்தையும் சேமி",

    collectionHistory: "சேகரிப்பு வரலாறு",
    rate: "விலை",
    weekTotal: "வார மொத்தம்",
    thisMonth: "இந்த மாதம்",
    goToPayments: "பணம் தாவலுக்குச் செல்",
    noRecordsYet: "பதிவுகள் இல்லை",

    totalExpected: "எதிர்பார்க்கும் தொகை",
    totalReceived: "பெறப்பட்டது",
    outstanding: "நிலுவை",
    paymentDate: "பணம் தேதி",
    periodFrom: "காலம் தொடக்கம்",
    periodTo: "காலம் முடிவு",
    milkmanName: "பால்காரர் பெயர்",
    expectedAmount: "எதிர்பார்க்கும் தொகை (₹)",
    receivedAmount: "பெறப்பட்ட தொகை (₹)",
    difference: "வேறுபாடு",
    paymentStatus: "நிலை",
    remarks: "குறிப்பு",
    paid: "செலுத்தப்பட்டது",
    partiallyPaid: "ஓரளவு செலுத்தப்பட்டது",
    pending: "நிலுவையில்",
    noPaymentsYet: "பணப் பதிவுகள் இல்லை",

    riceFeed: "கருக்கை தவிடு",
    normalFeed: "சாதாரண தவிடு",
    otherExpense: "இதர செலவு",
    expenseType: "வகை",
    feed: "தீவனம்",
    brownLeafRolls: "வாழை இலை உருட்டு",
    miscellaneous: "இதர",
    quantity: "அளவு",
    quantityOptional: "அளவு (கிலோ, விருப்பம்)",
    amount: "தொகை (₹)",
    vendorName: "விற்பனையாளர் பெயர்",
    description: "விவரம்",
    other: "மற்றவை",
    unit: "அலகு",
    expenseRecords: "செலவு பதிவுகள்",
    noExpensesYet: "செலவுகள் இல்லை",
    dateAmountRequired: "தேதி மற்றும் தொகை தேவை",
    veterinary: "கால்நடை மருத்துவர்",
    medicine: "மருந்து",
    vaccination: "தடுப்பூசி",
    ai: "செயற்கை கருவூட்டல்",
    shedMaintenance: "கொட்டகை பராமரிப்பு",
    editPayment: "பணத்தைத் திருத்து",
    qty: "அளவு",
    type: "வகை",

    salesHistory: "விற்பனை வரலாறு",
    rateperKg: "விலை/கிலோ (₹)",
    rateperBird: "விலை/பறவை (₹)",
    totalAmount: "மொத்த தொகை (₹)",
    buyerName: "வாங்குபவர் பெயர்",
    noSalesYet: "விற்பனைகள் இல்லை",
    byWeight: "எடை அடிப்படையில்",
    perBird: "ஒரு பறவைக்கு",
    numberOfBirds: "பறவைகள் எண்ணிக்கை",
    weightOrBirds: "எடை/எண்ணிக்கை",
    saleType: "வகை",

    farm: "நிலம்",
    farmLocation: "நிலம்",
    vendor: "விற்பனையாளர்",
    quoted: "மேற்கோள்",
    final: "இறுதி",
    quotedAmount: "மேற்கோள் தொகை (₹)",
    finalAmount: "இறுதி தொகை (₹, விருப்பம்)",
    itemDescription: "பொருள் விவரம்",
    accepted: "ஏற்றுக்கொள்ளப்பட்டது",
    rejected: "நிராகரிக்கப்பட்டது",
    totalAccepted: "ஏற்றுக்கொள்ளப்பட்டது",
    totalPending: "நிலுவையில்",
    totalRejected: "நிராகரிக்கப்பட்டது",
    finalAmountPrompt: "ஏற்றுக்கொள்ளப்பட்டதால் இறுதி தொகையை நிரப்பவும்",
    deleteConfirmExpense: "இந்த செலவை நீக்கவா?",
    deleteConfirmSale: "இந்த விற்பனையை நீக்கவா?",
    deleteConfirmRecord: "இந்த பதிவை நீக்கவா?",
    deleteConfirmPayment: "இந்த பணம் பதிவை நீக்கவா?",

    noCowsYet: "பசுக்கள் இல்லை. மேலே சேர்க்கவும்.",
    noGoatsYet: "ஆடுகள் இல்லை. மேலே சேர்க்கவும்.",
    noHensYet: "கோழிகள் இல்லை. மேலே சேர்க்கவும்.",
    nameGenderRequired: "பெயர் மற்றும் பாலினம் தேவை",
    dateRequired: "தேதி தேவை",
    rateDateRequired: "விலை மற்றும் தேதி தேவை",
    periodMilkmanRequired: "தேதி, காலம் மற்றும் பால்காரர் பெயர் தேவை",
    collectionFieldsRequired: "தேதி, காலை லிட்டர், மாலை லிட்டர் தேவை",
    paymentFieldsRequired: "பணம் தேதி மற்றும் பெறப்பட்ட தொகை தேவை",
    saveFailedMessage: "சேமிக்க முடியவில்லை. மீண்டும் முயற்சிக்கவும். / Could not save. Please try again.",
    electricity: "மின்சாரம்",
    water: "தண்ணீர்",
    labour: "கூலி",
    equipment: "உபகரணம்",
    repairs: "பழுது பார்த்தல்",
    transport: "போக்குவரத்து",
    allFarmsShort: "அனைத்தும்",
    editExpense: "செலவைத் திருத்து",
  },
} as const;

export type LabelKey = keyof typeof labels.en;

export function t(lang: Lang, key: LabelKey): string {
  return labels[lang][key];
}
